### ISSUE TITLE
[API, Webconfigurator] Posibility to configure docks.

### ISSUE THREAD

**Issue by nklerk** [YIO-Remote/remote-software#321]
Issue #319 should be accessible through the API/Confiurator to discover docks on the network.
Then it can configure config.json so the remote can contact the dock by implementing #320

**Comment by martonborzak** [comment]
You don't need to configure docks. The remote automatically discovers them on the networks and adds them. Only thing you need to configure is which dock is "paired" with the remote, for future use. Otherwise the remote is always connected to all the docks. 

MDNS discovery and creating integrations objects are done. 

Added commands to dock firmware to set friendly name, that is distributed through MDNS as well. Dock configuration should be done via web configurator and connecting directly to docks.
