### ISSUE TITLE
Separate integration library

### ISSUE THREAD

**Issue by ChristianRiedl** [YIO-Remote/remote-software#348]
Especially for the implementation  of integrations using **QAbstractListModel** like media players, weather, ... it  makes sense that every integration uses the same "model" classes.  I think the sources should be in a separate static **integration library**, not somewhere in the remote-software source hierarchy.

This integration library can also contain often used functionalities like OAuth, ...

The **Integration** base class should be there maybe extended to a more functional integration base class covering also the separate "integration thread".

**Comment by zehnm** [comment]
Further request for the separate library (or even an additional package like an integration-dev package): include all required header files to be able to compile the integration plugins.
I'm struggling at moment defining simple custom Buildroot packages for the integration plugins since the header files are in the software-remote module.

**Comment by zehnm** [comment]
To simplify the separation of the common interfaces and classes I will create the integration library as a _Qt Project Include_ (.pri) instead of a full blown static library.

With a static library we have another build dependency for 4 platforms and all existing build setups (Developer setup, GitHub Actions CI, Docker build image, Buildroot custom packages) need major work.
Once everything is working and the integration library contains more features we can think about a static library for ARM, macOS, Linux and Windows again.

**Comment by zehnm** [comment]
Pull requests for initial integration library refactoring created:
- All integration plugin related header files are now in the integrations.library.
- remote-software and all integrations are now using integrations.library.
- Integration plugins don't have a direct reference to remote-software anymore. Only to integrations.library.

Common plugin skeleton classes for plugin setup and threading will be integrated in a second step.

**Comment by martonborzak** [comment]
Can this be closed @zehnm ?

**Comment by zehnm** [comment]
It should auto-close once merged into master
