### ISSUE TITLE
General Logger enhancements

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#369]
I'm opening this issue to discuss and plan general enhancements for the `Logger` component.

Please add comments, further ideas or objections so we can specify all needed enhancements for the next release.
My suggestions and requirements are the following:

## Expected Behavior or Design

- Configurable filename
  The filename should be configurable, at least with a client settable prefix. Default: TBD.
  Reasons:
  - On the YIO remote the log files will be configured to be stored in /var/log.  
    They should have a prefix to easily distinguish them from other log files.
  - A prefix makes sure that the included file purger doesn't delete other files.
- Rolling file appender
  The hard coded 1 logfile per hour in `Logger::writeWile` needs to be configurable. Usually a rolling file logger is rolled over at midnight or after a certain file size has been reached. In my opinion one log file per hour is too much and the default of deleting files after 12 hours way too short.
- We need to discuss on how to handle file deletion.
  On Linux platforms I'd prefer to delete / archive them with default concepts, e.g. "logrotate". For other platforms we can still do it in the app. Therefore this needs to be configurable.
  - purgeHours == 0 disables purging.
  - Log deletion must be continuous (e.g. once a day). At the moment this is only done at Logger creation. This doesn't work for long uptimes and can create hundreds of files!
- `Logger` should be a pure utility class without dependencies to other YIO classes.  
  The Config dependency is already removed (see additional information below) but there's still a dependency to `PluginInterface`.
  - Q: Why is this dependency required? 
     In my opinion the registration should be handled outside of the logger: either the plugin loader registers the logging categories or we create a generic configuration option. Maybe I don't understand the concept but to me log categories are usually plain and simple in logging frameworks: each category has a configured log level. No need for callbacks into integration plugins. Example:

        logging: {
            categories: {
                Spotify: DEBUG,
                WifiCtrl: WARN,
                WpaCtrl: INFO,
                homeAssistant: CRIT
            }
        }

    The logging categories are default Q_LOGGING_CATEGORY and defined by the individual class(es). E.g. in wifi_wpasupplicant.cpp:

        static Q_LOGGING_CATEGORY(CLASS_LC, "WpaCtrl");
        
        qCWarning(CLASS_LC) << "Failed to establish connection to AP"

    Or is this not possible with the Logger? I.e. a category must be registered explicitly with the Logger and default Qt logging doesn't work?

## Possible Solution

The following a `logging` configuration section has already been added to config.json to configure the Logger:

```
    "settings": 
    {
        "language": "en_US",
        "autobrightness": true,
        "proximity": 40,
        "shutdowntime": 7200,
        "softwareupdate": false,
        "wifitime": 240,
        "bluetootharea": false,
        "paired_dock": "YIO-Dock-30AEA4D73C34",
        "logging": {
            "path": "/var/log",
            "level": "INFO",
            "console": true,
            "showSource": true,
            "queueSize": 100,
            "purgeHours": 72
        }
    },
```

Logger initialization in main.cpp:
```
    QMap<QString, QVariant> logCfg = config.getSettings().value("logging").toMap();
    Logger logger(logCfg.value("path", appPath + "/log").toString(),
                  logCfg.value("level", "WARN").toString(),
                  logCfg.value("console", true).toBool(),
                  logCfg.value("showSource", true).toBool(),
                  logCfg.value("queueSize", 100).toInt(),
                  logCfg.value("purgeHours", 72).toInt());
```

## Detailed Description and Additional Information

The following changes to the `Logger` component have already been done and commited to the develop branch:

- Renamed parameter `debug` to `console` which enables / disables console logging.  
   This was confusing and has nothing to do with debug in general. The console output is just another log destination. Note: on the remote the console log ends up in `journald`.

- Removed `Config` singleton dependency.  
  The `Logger` class should not depend on the `Config` class singleton. There's no need for the specific `Config` class and it makes it harder to test (Yes, unit tests are urgently needed for the whole project and will be introduced soon) and reuse.  
  -  The single "log" parameter which was read from `Config` is now the changed `logLevel` parameter. All other options were already constructor parameters or are available as setters. It's better to handle all configuration parameters the same way.
  - Future option: ONLY in case there will be many more parameters: 
    Provide a generic `const QVariantMap &config` parameter containing all logging related configuration options from `Config`. (Same concept as in HardwareFactory::build).

@martonborzak @nklerk @ChristianRiedl please review & comment.

**Comment by ChristianRiedl** [comment]
Here my comments : 

- Configurable filename : OK
- Rolling file behavior : 
Configurable rolling time interval + maximum size, OK
There is a allready a purgefile function intended for cyclical purging, which can be called cyclically. Who will call it ? Maybe there is somewhere a general daily cleanup function,  or I can create an internal timer. 
- Plugin interface dependence
Logging level of all registered categories are controlled per category by Logger class (and YioApi). 
Finally the logging will be shown in the web_configurator and it is very useful to **adjust the loglevels per category at runtime**.
This is the reason why Logger holds the references of the QLoggingCategory of all registered log "clients" ( *defineLogCategory   (const QString& category, ...*. Setting the loglevel for a category is not straight forward because the QMsgType is not ordered as expected, and I wanted to have this logic only on one place. For the integrations DLLs I did not want to keep such references to objects inside the dll. For this reason the *PluginInterface* has a method setLogEnabled to set the log level for the plugin.
When you declare the logging category with **Q_LOGGING_CATEGORY (name, "xxx")** you get a const reference and cannot call **setEnabled** and have to use the filter mechanism which is not well suited for our environment I think. When you declare the logging category **QLoggingCategory name ("xxx")** you can use it with the **qCDebug ... in the same way** and you **setEnabled**can be used. This is the reason why I went this way. And I was not sure if "logging category" registered by Qt inside a DLL can be controlled from outside.  
And my Logger class also gives an overview about all logger clients including per level counters. I did not find a Qt function to get all logger categories. This is the reason why logger clients in my concept register their category in Logger class. Integrations register their category implicitely with the PluginInterface. I do not see a real disadvantage doing it this way.

The changes you have made are OK for me I also dislike singletons.

**Comment by zehnm** [comment]
For the rolling file appender we can limit it to one simple option. It would be nice to have everything that e.g. [log4j in the Java world](https://www.baeldung.com/java-logging-rolling-file-appenders) provides, but we are not writing a generic logger library.

@martonborzak @nklerk what do you prefer? Size based - rotate after configurable amount, e.g. 10MB - or a fixed rotation at midnight?

In regards to setting the log level within integration plugins I first have to dig into how Qt logging works and understand the described issue in the last comment with QLoggingCategory.

**Comment by martonborzak** [comment]
Maybe size, I think.

**Comment by carp3-noctem** [comment]
Remove Split of Files at every hour

**Comment by carp3-noctem** [comment]
Add Manual Disconnect of integrations to logger (no logline is created at the moment)

**Comment by ChristianRiedl** [comment]
@zehnm 

Here a summary of my requirements and ideas, currently implemented in the apilogger feature branch.

- **Log targets** all category logs are routed via _qInstallMessageHandler_ to a central function which distributes the messages to targets which can be enabled / disabled by logger (and yio) api.
    - QtCreator Console 
    - Files (currently implemented writing normal files) can be replaced by journald
        - Configurable file name (directory and prefix)
        - Rolling files. I think a daily file is sufficient. Number of days kept is configurable. Old files are purged daily whenever a new file is created. 
        - Maybe a file size limit should be implemented 
     - Runtime log implemented by a queue with configurable size. Access by yio api for realtime display in web-configurator.

- **Per Category control**
    - Loglevel control per logger api and yio api (web-configurator)
    - Per loglevel counter. Would be nice to have a list of categories with counters and loglevel in web-configurator. Maybe makes sense to add a reset counter function.
    - Currently log filtering is done in the Logger::processMessage function. Some integrations want to log the whole message flow with _qCDebug_ which creates a significant load even when the debug loglevel is disabled. This can be avoided by enable/disable loglevels for the _QLoggingCategory_ objects. Qt does not provide suited methods for this purpose (https://bugreports.qt.io/browse/QTBUG-59853). Current Logger implementation does the job with _defineLogCategory_ function for integrations (via _PluginInterface_) and remote-software logs.

**Comment by zehnm** [comment]
@ChristianRiedl I haven't had the time yet to fully checkout your branch, especially the requirements or changes in the integrations.
I don't really understand the logging category definition within a plugin. In my opinion the definition needs to be in an external configuration file or env var, instead of hard coded in the source. Well, maybe I misunderstood it, I'll get to the code soon...

Nevertheless, I'd already like to provide some feedback and ideas.

For regular users and support issues I think it's important to add a log download option to web-configurator. This can be quite easily implemented once we integrate journald as logging backend:
1. query log messages within given date range (and hopefully on log level)
1. output to logfile
1. put (or directly write) logfile to a dedicated webserver directory
1. provide download link in web-configurator

I'll compile Qt with journald logging backend support when I get to updating Buildroot to 2020.02.x

In case we continue using the file logger, the following issues need to be addressed:
- Current log file may not include datestamp due to missing RTC.  
  Most of the time the initial file has a wrong date in the past, since NTP didn't set the current time yet.  
  During log file purging the current file will be deleted...
  Changes:
  - The active log file should only contain the prefix, e.g. yio.log
  - Afer roll-over the active file will be renamed with the timestamp.  
    This won't completely fix the issue, but if the remote hasn't been (re)booted around midnight, chances are high it has the correct time.  
- If the logfile cannot be written (e.g. wrong path) the console log is spammed with error messages.  
  The file target should be disabled if the file cannot be created and only one error message be printed. This is also the default behavior of other logging frameworks.


I'm not sure if realtime display of log messages in the web configurator is a priority.
But I could be mistaken.
What about a poll asking our users what they prefer?
If others are following this topic, then please comment on how you use or wish to use logging, to get a better understanding.
I'll also ask on Discord. Please feel free to also create a poll in the forum.

As a developer I'm quite happy with Qt's logging rules configuration options in QT_LOGGING_RULES environment variable (or qtlogging.ini): [Qt logging configuration categories](https://doc.qt.io/qt-5/qloggingcategory.html#configuring-categories).
To better use the filtering rules we should prefix all categories with `yio.` to have a global logging category since `*.debug=true` also enables Qt framework logging. (In Java it's common practice to use the full package name, which makes it super simple to log by domain / app / framework etc.).
The only downside for some devs might be the required app restart, if the rules are changed.
Personally, I have a ssh console open most of the time, tailing or grepping the log(s) while analyzing an issue.
It's also possible to start the app on the remote from Qt Creator and having the console redirected. Last but not least there's also remote debugging.

**Comment by ChristianRiedl** [comment]
@zehnm 
The central question for me is the requirement of a realtime log. I agree that for the **web-configurator** this feature has no high priority. The realtime log is helpful mainly for developers especially when testing on the YIO remote. Having a GUI which shows categories with per level counts and the realtime log and the possibility to change log levels  is **comfortable**. I am used to having such functions in a project, if not I implement it. For me as developer it is not important if it is part of the web-configurator as I implemented a small Qt app for this purpose which uses the YIOAPI (I could "beautify" it and make it available). This app also contains simulation of hardware buttons which is also useful when testing not on YIO remote.

When it is integrated in the web-configurator maybe some clever users can use it to analyse problems themselves (and so reduce the amount of required support).

There are also test cases where it is an advantage to change a log level without restarting the YIO remote.

In the "Adding unified logging" thread in the yio-community Niels and Marton ("Having log output to the web configurator would be a great addition") agreed and so I implemented it. I implemented 4 (including my "private" MQTT based) integrations (and planned to implement more ) and was very happy to use it. Now I see that a part of my implementation has been removed and I can't use the  logger as intended anymore. You can imagine that I was not "amused".

Qt logging rules and filters are not so easy to use so I implemented the initial log level of an integration as part of the plugin configuration (on the same level as "mdns"). This and the feature to change log level online from a UI made it necessary to add the **setLogEnabled** function to the **PluginInterface**. 

I agree that **journald** is a good replacement for the log files. 

If we continue to use the log files : Latest implementation does not delete the current file. Disabling log file writing if an error occurs because of wrong directory is easy to implement.

**Comment by zehnm** [comment]
I'm rewriting the Logger class this week since there have been no pull requests and on Discord users reported further issues and crashes in regards to logging.

Planned changes:
- Using journald as logging backend
  - Latest remote-os images have Qt journald support. Enabled with: `QT_LOGGING_TO_CONSOLE=0`
  - For this to work the default Qt message handler must be used, or at least chained within the current custom handler.
  - Configuration options to use custom files, journald, or both
- Replacing hard coded format pattern with the official `QT_MESSAGE_PATTERN` feature.
- Supporting `QT_LOGGING_RULES`
- Prefixing all logging categories with `yio.`
- Refactoring logging categories for easy filtering. E.g. `yio.hw`, `yio.hw.wifi`, `yio.intg`, etc.
