### ISSUE TITLE
Adding of Build Numbers to the Log as well as in Detailed Settings Page of Plugin

### ISSUE THREAD

**Issue by carp3-noctem** [YIO-Remote/remote-software#406]
**Is your feature request related to a problem? Please describe.**
When dealing with different Builds through testing / production it can be hard to get troubles in correct order when nobody knows which exact version is having the issue.

**Describe the solution you'd like**
a) During Plugin initialisation write Build number into Debug Log
b) Show Build number in detail view Page of Plugin details on Remote

**Describe alternatives you've considered**
Make them Available via a developer Page only

**Additional context**

**Comment by martonborzak** [comment]
Version number added to `.pro` file to keep track of versions.

**Comment by zehnm** [comment]
In remote-os I've added version number retrieval from Git Tags:
- release tag = main version number
- how many commits a develop build is ahead of the last release tag
- last commit hash if it's not a release build

See: [remote-os commit adaeebc](https://github.com/YIO-Remote/remote-os/commit/adaeebc9987ec969531afda2fdb0c4c0cffcdfd5)
Something similar needs to be included in remote-software and each integration plugin. For the software & plugin update feature the plugin interface need to be enhanced to return the version number (it the meta-interface doesn't include it already).
**This needs to be an automated solution (e.g. GitHub Action) and not set manually by the developer.**

**Comment by zehnm** [comment]
Git command to describe current version: `git describe --match "v[0-9]*" --tags HEAD`   
Example output: `v0.2.1-282-gefe76e9b`

- v0.2.1 = last version tag
- 282 = number of commits since last version
- gefe76e9b = last git commit hash

For this to work on the develop branch, it is essential to merge the release or master branch back to develop after it has been tagged. Otherwise the release tag is not 'reachable' by git describe and returns with error: fatal: No tags can describe '$HASH'. As a fallback the `--always` option can be added to just return the current commit hash.

Integration in the Qt .pro file should work with:
```
DEFINES +=
  APP_VERSION=\\\"$$system(git describe --match "v[0-9]*" --tags HEAD --always)\\\"
```

**Comment by zehnm** [comment]
- Version number is now accessible through the Qt plugin metadata.
- Plugin version is logged as INFO message before loading in Launcher.
- Functionality is in the develop branch of the integration plugins and the softwareupdate branch of remote-software.

Showing version number in Settings -> Integrations needs a few more enhancements. I therefore suggest opening a new feature request how exactly the information shall be presented in the UI.

@carp3-noctem please approve or comment
