### ISSUE TITLE
Remote intermittently stops responding when taken off charge

### ISSUE THREAD

**Issue by dakaix** [YIO-Remote/remote-software#462]
## Description
Am intermittently seeing the remote fail to respond after being lifted off of the dock. The screen shows the battery charge status or time + battery screen's and doesn't respond to touch or buttons. Have to SSH into the Pi and reboot it before the screen responds again

## How to Reproduce
1. Place remote on charge
2. Lift the remote out of the dock
3. Occasionally the screen stays in locked as though it's still on charge

## Expected behavior
Remote should respond quickly (if not immediately) to being taken off charge so that it is ready for use.

## Your Environment
* Version used: 0.3.1
* Running on: 
  - YIO Remote

**Comment by dakaix** [comment]
Tested now with 0.4.7, same behaviour exists however instead of showing the charging screen it will often show nothing at all.

**Comment by zehnm** [comment]
Additional information since I've noticed this bug as well once in a while:
- The issue seems with the battery qml card being "stuck" on top, but the app still reacts to touch input and gives haptic feedback.
- Sometimes it's "self healing": put it back in dock, wait a while, take it out and it works again as expected.

Unfortunately I could not find a way yet to re-produce it to track down the exact cause. Last time it happened was with the following steps:

1. Remote fully charged, switched off and sitting in dock
1. Switch on remote, leave it in dock
1. Wait until booted 
1. Take out of dock while the screen is still on
1. Stuck in battery screen

**Comment by martonborzak** [comment]
Please also provide logs from that time, so it's easier to track down the problem. Thanks!
