### ISSUE TITLE
Overflow (?) in climate entity widget

### ISSUE THREAD

**Issue by pr11me** [YIO-Remote/remote-software#485]
## Description
See attached images, huge number displayed. The temperature dial is not functional, it can be moved but does nothing and only the dial is displayed when dialing, no temperature. Also it is in max. position (approx. 5 o'clock ) and when moved counter-clockwise returns to this position immediately. Setting the temperature with DPAD up/down works, although one starts with 0 degrees. Once you set the temp. with DPAD, the value is persisted even if screen turns off but when climate card is closed and reopened the huge number is showed again and temp can be set with DPAD starting from 0. On the button which enters the card, the correct current temp. is displayed.

## How to Reproduce
1. Add climate entity from Home Assistant integration
2. Open the thermostat card

## Expected behavior
Ideally both the temp. setpoint and the current temp should be displayed on the card. The knob on the dial should stick at the setpoint, where its min and max position correspond to the min and max temp of the thermostat (markers would be helpful).

## Screenshots
![20200610_222041](https://user-images.githubusercontent.com/52279202/84317991-0234fa00-ab6e-11ea-9a42-0ba7eb5e02ab.jpg)
![20200610_222054](https://user-images.githubusercontent.com/52279202/84318007-082adb00-ab6e-11ea-99d4-4671992a4117.jpg)
![20200610_224030](https://user-images.githubusercontent.com/52279202/84318202-56d87500-ab6e-11ea-947d-1337a3ca0866.jpg)

## Your Environment

* Version used: 0.5.1
* Running on: 
  - YIO Remote
* thermostat: Google Nest 3rd gen UK import
https://www.amazon.de/gp/product/B01N282OF9/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

**Comment by pr11me** [comment]
The issue still persists.

**Comment by martonborzak** [comment]
Are you using the pre-release?

**Comment by pr11me** [comment]
Yes the latest.

**Comment by martonborzak** [comment]
this: Development Build 0.5.2-13-g8a5015eb ?

**Comment by pr11me** [comment]
Sry, I didn't properly merge into my fork...now I am up to date.

Well, now the card opens with 0 degrees and one cannot move the knob, although you get haptic feedback and the terminal shows 
"DEBUG homeassistant ThreadAdapter sendCommand "climate" "climate.living_room_thermostat" 4 QVariant(int, 2)"
where the number "2" is the current set temp. 

I think it's better if the card is set to the current temperature if opened, else one has to button way up to increase/decrease the temperature slightly.

Best would be if the current and set temperature were shown, where the latter needs to be remembered when the card is closed.

**Comment by zehnm** [comment]
@pri86 If the card shows 0 degree then the issue either comes from home-assistant not providing all values, or the defined climate entity is missing some supported_feature definitions in config.json.
How did you define the climate entity? By hand or with the web-configurator?
For all features to work with the UI it requires min-, max-, target- and temperature. Otherwise the knob doesn't work.

Example entity configuration in config.json for all features:
```
{
    "entities": {
        "climate": [
            {
                "entity_id": "webhook.climate.1",
                "friendly_name": "Test climate control",
                "integration": "webhook.1",
                "supported_features": [
                    "ON",
                    "OFF",
                    "COOL",
                    "HEAT",
                    "TARGET_TEMPERATURE",
                    "TEMPERATURE",
                    "TEMPERATURE_MIN",
                    "TEMPERATURE_MAX",
                    "HVAC_MODES"
                ]

            }
        ],
...
```
If this still shows 0 degrees, it means that home-assistant doesn't send the current temperature, or I introduced a new bug.
I'm currently writing the webhook integration and encountered all kinds of issues, if some of the "supported_features" were missing ;-)
Do you have a chance to check what home-assistant sends back?
If you are able to debug: homeassistant.cpp
- HomeAssistant::supportedFeatures ~ line 666 for supported features
- HomeAssistant::updateClimate ~ line 425 for returned values from HA  
  It should set: ClimateDef::TEMPERATURE, ClimateDef::TARGET_TEMPERATURE, ClimateDef::TEMPERATURE_MAX, ClimateDef::TEMPERATURE_MIN

It's possible that depending on the climate device or integration, that some values are not sent to YIO. In this case we'd have to work around it, to make the UI as functional as possible.

**Comment by pr11me** [comment]
Ah of course, thank you very much @zehnm, much appreciated. After adding the supported_features it works. Good job!

I noticed that while you can set the temp in increments of 0.5 degrees (which the nest supports), the command being sent truncates the value to int and also in the UI if you set it to x.5 it jumps to x.
