### ISSUE TITLE
Can Raspbirry 4 be supported later?

### ISSUE THREAD

**Issue by fengjiannan2010** [YIO-Remote/remote-software#495]
Hello, I am from China and I am very interested in seeing your project. Can I support Raspberry 4 in the future? YIO Store is temporarily unavailable and can open source PCB and 3d printing shells. Can support the official version of Raspbian system

**Comment by zehnm** [comment]
remote-software runs fine on RPi 4, there's not much to add, just the environment needs to be configured correctly:
- At least Qt 5.12.4 with all required add-ons and hardware accelerated eglfs support.
  - See Buildroot configuration in remote-os for required Qt libraries.
  - Qt 5.14 has not been tested yet.
- WiringPi must be installed.
- Hardware devices must be configured in hardware.json
  - Disable all devices (`"enabled": false`), otherwise there will be lots of timeout errors and the app runs slow or might even crash.
- For specific RPi4 device support you need to write a driver. See sources/hardware, especially the HardwareFactory class and its sub-classes for device specific support.

**Comment by zehnm** [comment]
Remote-software runs on RPi 4.
Closing due to duplicate, see instructions in #496
