### ISSUE TITLE
Rpi 4 And HDMI Display supported?

### ISSUE THREAD

**Issue by fengjiannan2010** [YIO-Remote/remote-software#496]
Hello, I have Raspberry Pi 4 and Raspberry Pi 3b devices, the supporting 7-inch LCD and HDMI display screens, can I add support? Or tell me the specific adaptation method, I have the ability to code. I will add some functions to adapt to China's smart home control, such as Xiaomi, Ali Smart, Tencent Smart. Thank you

**Comment by zehnm** [comment]
If you use Raspbian OS, then HDMI is supported out of the box, including common touch screens. I.e. if it's supported on Raspbian, then it also works on remote-software. See Qt documentation about additional screen & touch screen configuration with environment variables (QT_QPA_EVDEV_TOUCHSCREEN_PARAMETERS, QT_QPA_EGLFS_PHYSICAL_WIDTH, QT_QPA_EGLFS_PHYSICAL_HEIGHT, etc).:
- https://doc.qt.io/qt-5/inputs-linux-device.html
- https://doc.qt.io/qt-5/embedded-linux.html

The YIO remote-os is tailored to the YIO remote hardware devices and configuration. There are quite a few things you need to change, nothing too complicated if you have a good understanding of how the Raspberry boot configuration works:
- Change overlays
- Configure HDMI output instead of parallel display mode
- Remove display and touch initialization in app startup script and from systemd
- For USB touchscreen you need to add USB support in the kernel, then USB HID support etc.
- As mentioned in the other GitHub issue: configure hardware.json / write driver to support other hardware

**Comment by zehnm** [comment]
Closing issue because remote-software already runs on any RPi and on HDMI displays.
In remote-software only the `hardware.conf` configuration file needs to be adapted to a non remote-os environment. I.e. change or disable any devices or i2c buses. For hdmi, the display control needs to be disabled, otherwise it wants to communicate with the parallel display which leads to errors and timeouts.
