### ISSUE TITLE
Polling timer not working properly

### ISSUE THREAD

**Issue by miloit** [YIO-Remote/remote-software#519]
The polling timer isn't fired.

So that means no update by polling timer.

**Comment by zehnm** [comment]
@miloit Please fill out the bug template when opening an issue. We need more information and a detailed description so we can reproduce the issue and fix it. There are many timers at various places...

**Comment by miloit** [comment]
@zehnm I can not really fill out more I only tested it with an break point in the Qt creator. As well in the openhab binding no debug is written in the log.

**Comment by zehnm** [comment]
Well, with so little information I'm afraid I can't do anything, because I can't guess what the issue is.
What are you trying to achieve?
What doesn't work?
Where is the issue? Is it in remote-software, e.g. wifi polling, or inside an integration, e.g. connection polling?
Which polling timer? Source file? etc. etc.

**Comment by miloit** [comment]
it's running now after a restart
